"""Add user profile fields

Revision ID: 062ce3db990b
Revises: 
Create Date: 2025-01-08 19:33:09.094791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062ce3db990b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('unit_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('lease_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_joined', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_joined')
        batch_op.drop_column('lease_start')
        batch_op.drop_column('unit_number')
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
